/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7bea91d5-dfa5-4b8f-a736-6962ae881526",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FnUoKA2RU",
    "aws_user_pools_web_client_id": "103v0rmtujk4obn5vmdbkeeebj",
    "oauth": {
        "domain": "nexttailwindauth39eac99d-39eac99d-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://next-tailwind-auth-jjq1s2ebh-forgetscode.vercel.app/",
        "redirectSignOut": "https://next-tailwind-auth-jjq1s2ebh-forgetscode.vercel.app/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
